### ISSUE TITLE
Testing 

### ISSUE THREAD

**Issue by bsmit236** [briannasmithCOSC381/mini-canvas#1]
**User Story**
As a developer, I want to create tests that ensure the reliability of all classes.

**Persona**
A developer.

**Business Value**
Improves quality of code. 

**Feature**
Created unit tests for python code.

**Task List**
- [ ] Fix existing code 
- [ ] Create unit tests for python code 
- [ ] Run tests locally

**Acceptance Criteria**
1. Unit tests cover 95% + of all methods
2. All tests pass 

**Acceptance Tests**
1. Unit tests should cover all methods 
2. Run locally

issue #1
